name: Build Snake Wild Pro APK
on: [push, pull_request]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf cmake libtool pkg-config \
          libncurses5-dev libncursesw5-dev zlib1g-dev libffi-dev libssl-dev \
          build-essential python3-dev python3-pip python3-setuptools \
          libsqlite3-dev sqlite3 bzip2 libbz2-dev liblzma-dev libgdbm-dev \
          libnss3-dev libreadline-dev wget curl openjdk-17-jdk

      - name: Install Buildozer and Cython
        run: |
          pip3 install --user --upgrade "buildozer" "Cython<3.0"

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          # Solo ejecutamos la compilación directa, sin intentar limpiar carpetas inexistentes
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SnakeWildPro-Package
          path: bin/*.apk
